version: '3.8'

services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ys[PI[882NNo
      POSTGRES_DB: schema-manager
  gunicorn:
    build:
      context: ./
      dockerfile: docker/backend/Dockerfile
    env_file: .env
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn core.wsgi:application --bind=0.0.0.0 --log-level=debug --access-logfile='-' --error-logfile='-' --workers=2 --threads=5 --worker-class=gthread"
    volumes:
      - static-volume:/code/core/staticfiles/
    expose:
      - 8000
    depends_on:
      - db
  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - static-volume:/code/core/staticfiles/
    depends_on:
      - gunicorn
  celery:
    build:
      context: ./
      dockerfile: docker/backend/Dockerfile
    env_file: .env
    command: celery -A core worker --loglevel=info
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          memory: 4G
  redis:
    image: "redis:alpine"

volumes:
  postgres_data:
  static-volume:
